config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources "projects" do
  	resources "tasks" 
  end

  root "projects#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :tasks, dependent: :destroy
	accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
	has_one_attached :image
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new

    @project.tasks.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :complete, :image, tasks_attributes: [:id, :name, :description, :complete, :image, :_destroy])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :complete, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home Projects", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="hero-image">

    </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @project.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label "Project name", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label "Project description", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    
  </div>

  <div class="form-group">
    
      <%= f.label "Image upload", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.file_field :image, class: "form-control" %>
      </div>
    
  </div>
  
  <div class="form-group">

      <div class="col-sm-offset-2 col-sm-10"> 
        <div class="checkbox">
          <label>
            <%= f.check_box :complete %>
            <span style="vertical-align: sub;">Project complete?</span>
          </label>
        </div>
      </div>
    
  </div>

  <div class="form-group">
    <div class="col-sm-2 control-label"> 
      <h3>Tasks</h3>
    </div>
  </div>
  
  <div id='tasks'>
    <%= f.fields_for :tasks do |task| %>
      <%= render 'task_fields', :f => task %>
    <% end %>
    <div class='links'>
      <div class="form-group">
      <div class="col-sm-2 control-label">
      <%= link_to_add_association 'add task', f, :tasks %>
      </div>
      </div>
    </div>
  </div>
  

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/projects/_task_fields.html.erb
  <div class='nested-fields'>
    <div class="form-group">
      	<%= f.label "Task name", class: "col-sm-2 control-label" %>
      	<div class="col-sm-10">
      		<%= f.text_field :name, class: "form-control" %>
  		</div>
    </div>
    <div class="form-group">
      	<%= f.label "Task Description", class: "col-sm-2 control-label" %>
      	<div class="col-sm-10">
      	<%= f.text_area :description, class: "form-control" %>
      	</div>
    </div>
    <div class="form-group">
      	<div class="col-sm-offset-2 col-sm-10"> 
	        <div class="checkbox">
	          	<label>
	            <%= f.check_box :complete %>
	            <span style="vertical-align: sub;">Task complete?</span>
	          	</label>
	        </div>
	     </div>

    </div>
    <div class="form-group">
    <div class="col-sm-2 control-label">
    <%= link_to_remove_association "remove task", f %>
    </div>
	</div>
  </div>

app/views/projects/edit.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @project, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing project</h1>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header">
  <%= link_to new_project_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Project
  <% end %>
  <h1>Listing projects</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Complete</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <%= content_tag :tr, id: dom_id(project), class: dom_class(project) do %>
                      <td><%= project.name %></td>
                      <td><%= project.description %></td>
                      <td><%= project.complete == true ? "Yes" : "Not yet" %></td>
                    <td><%= link_to 'Show', project %></td>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New project</h1>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_project_path(@project), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show project</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @project.name %></dd>

  <dt>Description:</dt>
  <dd><%= @project.description %></dd>

  <dt>Complete:</dt>
  <dd><%= @project.complete == true ? "Yes" : "Not yet" %></dd>

    <% if @project.image.attached? %>
    <img src="<%= (url_for(@project.image)) %>">
  <% end %>

</dl>

app/views/tasks/_form.html.erb
<%= form_for(@task, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @task.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h4>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <div class="col-sm-offset-2 col-sm-10"> 
        <div class="checkbox">
          <label>
            <%= f.check_box :complete %>
            Complete      
          </label>
        </div>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :project, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :project, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @task, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <%= link_to new_task_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Task
  <% end %>
  <h1>Listing tasks</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Complete</th>
            <th>Project</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <%= content_tag :tr, id: dom_id(task), class: dom_class(task) do %>
                      <td><%= task.name %></td>
                      <td><%= task.description %></td>
                      <td><%= task.complete %></td>
                      <td><%= task.project %></td>
                    <td><%= link_to 'Show', task %></td>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New task</h1>
</div>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_task_path(@task), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show task</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @task.name %></dd>

  <dt>Description:</dt>
  <dd><%= @task.description %></dd>

  <dt>Complete:</dt>
  <dd><%= @task.complete %></dd>

  <dt>Project:</dt>
  <dd><%= @task.project %></dd>

</dl>